# Generated by Django 5.2.2 on 2025-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_usuario", models.IntegerField()),
                ("nome", models.CharField(max_length=10)),
                ("bio", models.TextField(max_length=200)),
                ("foto", models.CharField()),
            ],
        ),
    ]
