# Generated by Django 5.2.2 on 2025-06-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("capa", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("letra", models.TextField()),
                ("duracao", models.IntegerField()),
                ("capa", models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="id_usuario",
        ),
        migrations.AddField(
            model_name="usuario",
            name="critico",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("foto", models.CharField()),
                (
                    "albuns",
                    models.ManyToManyField(blank=True, null=True, to="api_bb.album"),
                ),
                ("generos_artista", models.ManyToManyField(to="api_bb.genero")),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="genero_album",
            field=models.ManyToManyField(to="api_bb.genero"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="genero_favoritos",
            field=models.ManyToManyField(to="api_bb.genero"),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(max_length=200)),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                ("nota", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_bb.album",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_bb.usuario"
                    ),
                ),
                (
                    "musica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_bb.musica",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="faixa",
            field=models.ManyToManyField(to="api_bb.musica"),
        ),
    ]
