# Generated by Django 5.2.2 on 2025-07-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0002_alter_usuario_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
        ),
    ]
