# Generated by Django 5.2.2 on 2025-06-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0002_album_genero_musica_remove_usuario_id_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="albuns",
            field=models.ManyToManyField(blank=True, to="api_bb.album"),
        ),
    ]
