# Generated by Django 5.2.2 on 2025-06-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0003_alter_artista_albuns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="genero_favoritos",
            field=models.ManyToManyField(blank=True, to="api_bb.genero"),
        ),
    ]
