# Generated by Django 5.2.2 on 2025-06-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0004_alter_usuario_genero_favoritos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="genero_favoritos",
            new_name="generos_favoritos",
        ),
    ]
