# Generated by Django 5.2.2 on 2025-06-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_bb", "0005_rename_genero_favoritos_usuario_generos_favoritos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="capa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="artista",
            name="foto",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="musica",
            name="capa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="musica",
            name="letra",
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.CharField(max_length=200),
        ),
    ]
